wheremyfoodat/Panda3DS

include/helpers.hpp
This is needed to not rely on implementation defined behavior regarding transitive header includes, here for std::integer_sequence.
=> Fix GCC build error by correctly including `<utility>` header

readme.md
These directions are incorrectly using `cmake .` when it should be
`cmake ..`.
=> Fix cmake out-of-source build instructions

include/PICA/shader.hpp, include/helpers.hpp, src/core/PICA/gpu.cpp, src/core/PICA/regs.cpp, src/core/PICA/shader_interpreter.cpp, src/core/loader/lz77.cpp, src/core/renderer_gl/etc1.cpp, src/core/renderer_gl/renderer_gl.cpp, src/core/renderer_gl/textures.cpp
`constexpr` functions for extractint bitfields that lends itself a bit
better to emitting instructions like `bextr` on x86 or `ubfx` on arm64.
And may subjectively make things a bit more readable.
"Extract `5` bits" rather than `& 0x1F`.
=> Add `Helpers:{getBits,getBit}`

src/core/fs/archive_save_data.cpp
Based on `ExtSaveDataArchive::createFile`. Gets some games farther that
try to create save-data upon boot.
=> Implement `SaveDataArchive::createFile`

.clang-format
Used the command `clang-format -i tests/**/*.c src/**/*.cpp include/**/*.hpp` to process all of the project's files.
Using the one from [pcsx-redux](https://github.com/grumpycoders/pcsx-redux/blob/main/src/.clang-format)as a basis and then made additional edits to be the _least_ disruptiveto the pre-existing formatting patterns.
Open to additional edits.
=> Add `.clang-format`

include/PICA/regs.hpp
This enum was using the `u32` type without including `helpers.hpp`, causing sensitivity to include-order. Headers should be very self-contained to avoid this issue.
=> Add missing header for regs.hpp

.clang-format, include/opengl.hpp, include/renderer_gl/renderer_gl.hpp, src/core/PICA/gpu.cpp, src/core/PICA/regs.cpp, src/core/renderer_gl/renderer_gl.cpp
Starts utilizing [std::span](https://en.cppreference.com/w/cpp/container/span) to indicate a non-owning view of a contiguous array of elements rather than `T* data, usize count`.
=> Use `std::span` to pass vertex data

include/cpu_dynarmic.hpp, include/kernel/kernel.hpp, include/services/service_manager.hpp, src/core/kernel/threads.cpp, src/core/services/service_manager.cpp
Following the trend of #33: `std::span` provides some useful utility functions like `size_bytes()` and `as_bytes()` and serves as a better non-owning "chunk of data"-type over just passing around an `std::array&`.
=> Use `std::span` for CPU register-state

include/helpers.hpp
Tested on Fedora 38, helpers.hpp was missing an import.
=> fix: fix build on Linux with gcc

include/helpers.hpp, src/core/kernel/threads.cpp, src/core/services/cfg.cpp, src/core/services/hid.cpp
Allows compilation on native macOS build system.
Add workaround helper for bit_cast and missing #include <bit> header. 
This PR doesn't have the detection and replacement of the bit_cast with std::bit_cast, which is left as a TODO item.
=> Work around compilation errors on macOS

include/PICA/gpu.hpp, include/PICA/regs.hpp, include/renderer_gl/renderer_gl.hpp, include/renderer_gl/surfaces.hpp, include/renderer_gl/textures.hpp, src/core/PICA/gpu.cpp, src/core/PICA/regs.cpp, src/core/renderer_gl/renderer_gl.cpp, src/core/renderer_gl/textures.cpp
Slowly stepping the codebase towards having renderer-agnostic types and keeping the translation of PICA-types to OpenGL/VK/DX/Software/etc to the renderer-backend.
=> Add PICA texel-format and topology types

CMakeLists.txt, include/opengl.hpp
Adds `OpenGL::setObjectLabel` and `OpenGL::DebugScope` for naming OpenGL-objects and grouping scopes of commands to help with debugging and captures.
Both support printf-style formatting and use the appropriate function-attributes and will emit warnings if the specifiers and type do not match up. `OpenGL::DebugScope` is a raii-based wrapper around `gl{Push,Pop}DebugGroup` allowing one to simple create a `OpenGL::DebugScope` object with the formatted name and it will automatically Push/Pop the scope.
This is just the utility functions, I'll let the actual naming/scoping come later.
=> Add OpenGL object-naming and scoping

CMakeLists.txt, include/crypto/aes_engine.hpp, include/emulator.hpp, include/helpers.hpp, include/loader/ncch.hpp, include/memory.hpp, include/metaprogramming.hpp, src/core/crypto/aes_engine.cpp, src/core/fs/archive_ncch.cpp, src/core/fs/archive_self_ncch.cpp, src/core/loader/ncch.cpp, src/core/loader/ncsd.cpp, src/emulator.cpp, src/main.cpp
This adds support for encrypted NCSD files.
We loads keys from `<data_dir>/Alber/sysdata/aes_keys.txt`.
NOTE: We do differ from other emulators by not hard-coding the `generator` key, it's the user responsibility to provide it in `aes_keys.txt`.
NOTE: This is missing NCCH version 1 support and seeded crypto but that would be enough for now.
=> feat: Add support for encrypted NCSD

include/emulator.hpp, include/services/hid.hpp, include/services/service_manager.hpp, src/emulator.cpp
This PR adds basic controller support with a hardcoded keymap that tries to map it as close to the physical layout on the 3DS as I could.
Buttons and circle pad are mapped, touchpad and motion sensors are not supported. Controller hot-plugging should work, though only the first controller index SDL2 sees will be used.
=> Add basic controller input using the SDL2 GameController API

CMakeLists.txt, include/emulator.hpp, include/io_file.hpp, src/emulator.cpp, src/io_file.cpp, src/main.cpp
Makes the implementation of `IOFile` private, allowing inclusions and defines such as `#define fseeko` and `#include <io.h>` to not poison client-code or the global namespace.
=> Migrate `IOFile` implementation to `io_file.cpp`

.gitignore
Makes it extra :sparkles: reliable :sparkles:
=> Add slash to CLion build folders' .gitignore line

CMakeLists.txt, include/PICA/gpu.hpp, include/PICA/pica_vertex.hpp, include/renderer_gl/renderer_gl.hpp, src/core/PICA/gpu.cpp, src/core/PICA/regs.cpp, src/core/renderer_gl/renderer_gl.cpp
Get rid of the OpenGL intermediate vertex struct and replace it with a generic vertex struct in Pica's native format. 
Benefits: 
- Faster as it removes some copies
- Makes the code more renderer independent as gpu.hpp and gpu.cpp no longer have that OGL dependency. 
- Pipelines the needed attributes for lighting
- Less code :)
=> Refactored Vertex Pipeline to always use Pica Formatted Vertex

include/renderer_gl/renderer_gl.hpp, include/renderer_gl/surface_cache.hpp, src/core/renderer_gl/textures.cpp
Implemented as a simple ring buffer evicting the oldest entry for now. 
Should eliminate all texture related "Surface cache full! Add emptying!" errors
=> [GPU] Add texture surface cache eviction

include/emulator.hpp, include/services/hid.hpp, include/services/service_manager.hpp, readme.md, src/core/services/hid.cpp, src/emulator.cpp
This makes right click + mouse swipe report as a 3DS rotation. It's not quite great yet because the proper math is horrible (currently relative rotation angle is hardcoded based on the relevant mouse motion direction vector) and mapping euler angles to mouse swipes is not a particularly fun experience, but it seems to work for games that need situational gyroscope input like Kirby Triple Deluxe.
=> Initial gyroscope support

src/config.cpp
The non-error-code version of these functions are susceptible to throwing an exception in the case of system errors like permission issues or underlying device errors.
=> config: Use `error_code` prototype of `filesystem::exists`

CMakeLists.txt
Speed up our compilation by about 20 files by removing the need to compile all of SDL's test suite.
=> Disable compilation of SDL tests

include/PICA/gpu.hpp, include/helpers.hpp, include/memory.hpp, src/core/fs/archive_ncch.cpp, src/core/fs/archive_self_ncch.cpp, src/core/kernel/file_operations.cpp, src/core/kernel/threads.cpp, src/core/loader/lz77.cpp, src/core/memory.cpp, src/core/renderer_gl/etc1.cpp, src/core/renderer_gl/renderer_gl.cpp, src/core/renderer_gl/textures.cpp, src/core/services/dsp.cpp, src/core/services/fs.cpp
Just some janitorial stuff involving implicit casting from int/float types into smaller-types(lossy casting).
Particularly all of the [C4267](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4267?view=msvc-170) and [C4244](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-levels-3-and-4-c4244?view=msvc-170) warnings.
=> Address `C4267`/`C4244` warnings

include/emulator.hpp, include/services/gsp_gpu.hpp, src/core/services/gsp_gpu.cpp, src/emulator.cpp, src/main.cpp
Or by dragging and dropping onto executable file. Instead, open a blank window and use SDL's drag&drop feature.
Kinda hacky right now (lots of repeated if's with the same condition to just not run the emulator's things when a rom isn't loaded)
=> Don't force users to load rom from terminal

CMakeLists.txt, src/emulator.cpp, src/stb_image_write.c
Rather than having the entire implementation within `emulator.cpp`, causing incremental builds to be much slower, give it its own translation unit `stb_image_write.c`.
=> Move `stb_image_write` into its own translation unit

src/core/kernel/kernel.cpp
`delete`-ing a `void*` is undefined behaviour.
Alternatively you can define a base class with a virtual destructor for the payload types.
=> kernel: Delete object properly in deleteObjectData

CMakeLists.txt, include/config.hpp, include/emulator.hpp, include/renderer.hpp, include/renderer_gl/renderer_gl.hpp, include/renderer_null/renderer_null.hpp, src/config.cpp, src/core/PICA/gpu.cpp, src/core/renderer_gl/renderer_gl.cpp, src/core/renderer_null/renderer_null.cpp, src/emulator.cpp, src/main.cpp, src/renderer.cpp
This adds the null rendering backend, which just stubs all of the implementation details of the rendering backend, allowing for "headless" emulation of 3DS roms.
This also adds support for multiple rendering backends, based on an index within the user's `config.toml`.
=> Add a `null` rendering backend

CMakeLists.txt, include/action_replay.hpp, include/cheats.hpp, include/emulator.hpp, src/core/action_replay.cpp, src/core/cheats.cpp, src/emulator.cpp
Add basic framework for cheats + support for some simpler ActionReplay (CTRPF) cheat codes.
Note: Some AR cheats rely on things such as linear heap mapping being 1-1 with retail kernel and as such don't work. Also cheats are not yet hooked to the GUI.
=> Add preliminary cheat support

.gitmodules, CMakeLists.txt, include/renderer.hpp, include/renderer_sw/renderer_sw.hpp, src/core/PICA/gpu.cpp, src/core/renderer_sw/renderer_sw.cpp, src/emulator.cpp, src/renderer.cpp
Adds an empty sw renderer backend properly hooked to the frontend and config file + a glm submodule for vector and quaternion math
=> SW renderer infrastructure

include/emulator.hpp, include/httpserver.hpp, include/services/hid.hpp, src/emulator.cpp, src/httpserver.cpp
Improvements:
- Remove Emulator::pollHttpServer function as it did not belong inside Emulator, instead give HttpServer a pointer to emulator
- Create an HttpAction class which each type of action (more to be added) derives
- Instead of a single request, can now queue many requests in a (hopefully) thread safe queue and execute them whenever polled
- Use RAII for starting and stopping the server
- Cleaner HttpServer class overall
- Added function that checks if a button is pressed in hid.hpp
=> Refactor http server

.gitignore, CMakeLists.txt, include/compiler_builtins.hpp, include/helpers.hpp, include/kernel/kernel.hpp, include/logger.hpp
There used to be an "issue" with user builds where even if a logger is disabled at compile time, the compiler can't fully understand that due to being unable to inline non-trivial functions with variadic arguments. Thus, even for a disabled log call, the compiler would emit a call to a thunk function, which would then call the actual log function, which would then simply return.
This is fixed in this PR (in a way that I am not a huge fan of, but whatever) by making the log functions trivial and inlineable when compiling a user-facing build unless they are generated with `MAKE_LOG_FUNCTION_USER`.
This should remove this overhead from user-facing builds (it persists with dev builds, but it doesn't matter, really).
All of this research was performed on MSVC but I suspect similar things …
=> Remove logging overhead in user builds & update gitignore

include/PICA/dynapica/shader_rec_emitter_x64.hpp, include/PICA/shader.hpp, include/kernel/kernel.hpp, src/core/PICA/dynapica/shader_rec_emitter_x64.cpp, src/core/kernel/address_arbiter.cpp, src/core/kernel/events.cpp, src/core/kernel/kernel.cpp, src/core/kernel/ports.cpp, src/core/kernel/threads.cpp, src/emulator.cpp, src/host_shaders/opengl_fragment_shader.frag
Various changes to the thread scheduler. Fixes or improves a bunch of games including the following
- Captain Toad Treasure Tracker
- Sonic Boom something about Crystals
- Fire Emblem Awakening (probably Fates too)
- Rhythm Heaven Megamix (USA only)
- Bust-A-Move Universe
- Nintendogs
- Probably a lot more
This is still WIP and won't be merged until all regressions are fixed and some stubborn games are fixed
Partially covers #124
=> [WIP] Multithreading fixes

src/core/memory.cpp
Gets Virtual Console titles to do things (Pokemon Crystal VC below)
=> Change shared memory remap panic to warning

.gitmodules, CMakeLists.txt, include/config.hpp, include/discord_rpc.hpp, include/emulator.hpp, src/config.cpp, src/discord_rpc.cpp, src/emulator.cpp
To address any potential privacy concerns
- Discord RPC is an opt-in feature that is off by default. You must turn it on yourself in the config file (or in the future GUI)
- If that is not enough, there is a CMake option for enabling/disabling whether RPC support should be compiled in at all
This is how the RPC looks in Discord
=> Add Discord RPC

include/loader/ncch.hpp, include/memory.hpp, src/core/loader/elf.cpp, src/core/loader/ncch.cpp, src/core/loader/ncsd.cpp, src/core/memory.cpp
This fixes compatibility issues with various games that have internal region lock, such as Luigi's Mansion or Rhythm Heaven Paradise/Megamix
=> Autodetect 3DS region and properly report it in CFG::SecureInfoGetRegion

include/services/fs.hpp, src/core/services/fs.cpp
This PR partially implements the aforementioned FS calls but we can't properly implement them until I rework some more filesystem stuff. I have included some info for implementing it in the source however.
Gets Planet Robobot retail in-game
=> Partially implement FS::{Create/Delete}ExtSaveData

include/renderer_gl/renderer_gl.hpp, src/core/renderer_gl/renderer_gl.cpp
The behaviour emulated isn't 1:1 with original hardware since the original hardware behavior is impossible to emulate with OpenGL (or Vulkan, or any other graphics API). However returning blank should be fine (Citra does similarly)
Fixes Cars 2, gets Tomodachi Life to the creating save data screen, is one of the things needed to get Pokemon XY working
=> Implement reading texture from NULL

src/core/kernel/ports.cpp
Some games like Arc Baseball use invalid handles...
=> Make SendSyncRequest warn instead of panic on invalid handles

src/core/kernel/resource_limits.cpp
Fixes farm simulator 18 (never make me play this game again)
=> Add resource limit for threads to getResourceLimitLimitValues

include/services/hid.hpp, src/emulator.cpp
The current implementation of the TSC simply sets the touchscreen coordinates when the left mouse click is first pressed, not accounting for dragging it across the screen. This fixes that and makes games like Mickey Mouse's drawing minigame completable
=> [Touchscreen] Properly handle "dragging" stylus across screen

src/host_shaders/opengl_vertex_shader.vert
Fixes the stars in Cut the Rope. std::min cannot be used because color may be NaN
=> gpu: Saturate color before interpolation

CMakeLists.txt, include/emulator.hpp, include/fs/archive_ncch.hpp, include/fs/archive_self_ncch.hpp, include/loader/3dsx.hpp, include/memory.hpp, readme.md, src/core/fs/archive_ncch.cpp, src/core/fs/archive_self_ncch.cpp, src/core/loader/3dsx.cpp, src/core/memory.cpp, src/emulator.cpp
3DSX-embedded romFS works (tested with the gpusprites and cubemap example from 3ds-examples)
Haven't tested if this affected other file formats, it shouldn't.
Maybe the cxi romfs loading, since that was moved into a if statement, but I heavily doubt it, Still a good idea to test if you can :)
Pretty much entirely adapted from Luma3DS's loader reimpl 3dsx loading code, thanks @TuxSH for that bit of GPLv3 wisdom
=> added feature: 3dsx loading

CMakeLists.txt, include/emulator.hpp, include/fs/archive_ext_save_data.hpp, include/kernel/kernel.hpp, include/services/amiibo_device.hpp, include/services/nfc.hpp, include/services/service_manager.hpp, src/core/services/amiibo_device.cpp, src/core/services/nfc.cpp, src/emulator.cpp
Can get games like Captain Toad to recognize and attempt to parse the Amiibo, but not quite parse it yet.
For now Amiibo are detected by dragging and dropping an `.amiibo` file on the emulator window. This is the same as the usual .bin format, but renamed for ease of implementation. Bin files can be very easily supported when a proper GUI with a button to load amiibi is added.
Also stubs a small problem for @noumidev
=> More amiibo work

include/lua.hpp, src/emulator.cpp, src/lua.cpp
This lets us get our first mods running.
Example code (Decrement rupee counter by 1 in OoT)
```lua
-- Addresses storing rupees
rupees1_address = 0x050AF88
rupees2_address = 0x05879A0
-- Decrement both rupee counters by 1
write16(rupees1_address, read16(rupees1_address) - 1)
write16(rupees2_address, read16(rupees2_address) - 1)
```
=> Hook memory RW to Lua

include/fs/archive_system_save_data.hpp, src/core/fs/archive_system_save_data.cpp
Fixes game notes on my local, needs some stuff done to work on upstream
=> Add SystemSaveData::CreateDirectory

include/fs/archive_ext_save_data.hpp, include/result/result_fs.hpp, src/core/fs/archive_ext_save_data.cpp
=> Implement RenameFile for ExtSaveData

include/result/result_common.hpp
Fixes arm gcc getting mad due to the default constructor not actually producing a constexpr result
=> Result: Initialize m_value to 0 in default HorizonResult constructor

src/core/kernel/threads.cpp
For whatever reason when compiling on MacOS x86_64 (probably on an old compiler, it's a VM) I would get this error
This commit fixes this, compiles fine for me now.
=> Fix ambiguity between enum and type

include/services/y2r.hpp, src/core/services/y2r.cpp
Used by Street Fighter IV and more.
Sadly Street Fighter IV needs some more KTimer fixes to fully go in-game, since it uses timers to time the opening FMV which doesn't work with the current timer stub.
=> Add more HLE Y2R functions

include/kernel/kernel.hpp, src/core/kernel/kernel.cpp, src/core/kernel/timers.cpp
Required for various games like Pokemon Dream Radar, Kid Icarus, FIFA et al
Fixes some of them on my local with a small timer scheduling stub, which I won't push so upstream will have to wait for a proper scheduler to be implemented
=> Better KTimer implementation 

src/core/kernel/events.cpp, src/core/services/ir_user.cpp
Fixes games stuck polling IR (eg Majora's Mask 3D) and other games that may have been broken due to WaitSync timeouts not working
=> Fix Kernel WaitSynchronization1 HLE, properly report CirclePadPro as not connected

.gitmodules, CMakeLists.txt, include/emulator.hpp, include/lua_manager.hpp, include/panda_qt/main_window.hpp, include/panda_qt/text_editor.hpp, src/lua.cpp, src/panda_qt/main_window.cpp, src/panda_qt/text_editor.cpp, src/panda_qt/zep.cpp
This PR adjusts panda-sdl's scripting engine for panda-qt
This includes
- Built-in text editor for Lua files
- Syntax highlighting
- Ability to load `.lua` and `.txt` files from the filesystem, similar to panda-sdl. Loaded Lua files are also mirrored in the built-in text editor so you can load a .lua file and edit it inside the emulator..
=> [Qt] Full scripting integration

include/kernel/kernel.hpp, src/core/kernel/kernel.cpp, src/core/kernel/threads.cpp
K11 decomp seems to indicate that svcGetThreadContext is not a stub in the actual retail kernel, but this seems to work fine enough for now. Added a warning in case it needs to be revisited, still
=> Implement SVC 0x3B (GetThreadContext)

CMakeLists.txt, include/cpu_dynarmic.hpp, include/emulator.hpp, include/kernel/kernel.hpp, include/kernel/kernel_types.hpp, include/scheduler.hpp, src/core/CPU/cpu_dynarmic.cpp, src/core/kernel/timers.cpp, src/emulator.cpp
Currently only handles VBlank and KTimer events. Fixes or at least improves emulation of most games that use KTimer (Pokemon Dream Radar, Kid Icarus, SFIV, etc)
PR should probably add idle skipping and the like before being deemed mergeable
=> Add basic event scheduler functionality

CMakeLists.txt, include/applets/applet.hpp, include/applets/applet_manager.hpp, include/applets/error_applet.hpp, include/applets/mii_selector.hpp, include/applets/software_keyboard.hpp, include/kernel/handles.hpp, include/kernel/kernel.hpp, include/memory.hpp, include/services/boss.hpp, include/services/gsp_gpu.hpp, include/services/ptm.hpp, src/core/applets/applet_manager.cpp, src/core/applets/error_applet.cpp, src/core/applets/mii_selector.cpp, src/core/applets/software_keyboard.cpp, src/core/kernel/kernel.cpp, src/core/kernel/memory_management.cpp, src/core/services/apt.cpp, src/core/services/boss.cpp, src/core/services/gsp_gpu.cpp, src/core/services/ptm.cpp
Fixes a lot of games that require those eg
- Super Mario 3D Land (retail)
- Tekken 7
- Terraria
- Final Fantasy Explorers
- Hatsune Miku DX
- Mii Maker
- Rhythm Heaven
And many more.
Tomorrow I will add the EULA agreement applet which should get Rhythm Heaven fully in-game and probably fix more games. Thanks to libcru and citra for a bunch of the applet definitions and misc RE work
=> Add support for software keyboard & mii selector applets, improve APT/PTM/BOSS/misc HLE

include/cpu_dynarmic.hpp, include/kernel/kernel.hpp, include/kernel/kernel_types.hpp, src/core/kernel/events.cpp, src/core/kernel/idle_thread.cpp, src/core/kernel/threads.cpp
Skips the time software is spent idling better, leading to up to 5x less CPU usage depending on the software running and better performance on Android when combined with the arm64 shader JIT.
=> Add idle skipping

src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/GameActivity.java, src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/base/BasePreferenceFragment.java, src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/main/SettingsFragment.java, src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/preferences/AdvancedPreferences.java, src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/preferences/AppearancePreferences.java, src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/preferences/ControllerMapperPreferences.java, src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/preferences/InputMapPreferences.java, src/pandroid/app/src/main/res/drawable/color_surface.xml, src/pandroid/app/src/main/res/drawable/switch_thumb.xml, src/pandroid/app/src/main/res/drawable/switch_track.xml, src/pandroid/app/src/main/res/layout-land/activity_main.xml, src/pandroid/app/src/main/res/layout/activity_input_map.xml, src/pandroid/app/src/main/res/layout/activity_main.xml, src/pandroid/app/src/main/res/layout/activity_preference.xml, src/pandroid/app/src/main/res/layout/fragment_search.xml, src/pandroid/app/src/main/res/values-pt-rBR/strings.xml, src/pandroid/app/src/main/res/values-v27/themes.xml, src/pandroid/app/src/main/res/values-v29/themes.xml, src/pandroid/app/src/main/res/values/strings.xml, src/pandroid/app/src/main/res/values/themes.xml, src/pandroid/app/src/main/res/xml/advanced_preferences.xml, src/pandroid/app/src/main/res/xml/start_preferences.xml
- Fix navigation bar pr #381 crashes on android 8 or lowness
- Fix android 7 ui render
- Fix BottomNavigationBar color in some devices
- Fix inconsistent icon size in search category
- Fix navigation bar color in GameActivity caused by #381 
- Change switch widget to modern style.
- Rename "Developer options" to "advanced options".
=> Pandroid: Fix Navigation bar.

.gitmodules, CMakeLists.txt, include/audio/dsp_core.hpp, include/audio/null_core.hpp, include/audio/teakra_core.hpp, include/config.hpp, include/emulator.hpp, include/kernel/kernel.hpp, include/kernel/kernel_types.hpp, include/logger.hpp, include/memory.hpp, include/scheduler.hpp, include/services/dsp.hpp, include/services/service_manager.hpp, src/config.cpp, src/core/audio/dsp_core.cpp, src/core/audio/null_core.cpp, src/core/audio/teakra_core.cpp, src/core/kernel/events.cpp, src/core/memory.cpp, src/core/services/dsp.cpp, src/core/services/gsp_gpu.cpp, src/emulator.cpp
This PR is the first step for full audio support and for fixing games that are still broken due to needing feedback from the DSP (eg Pokemon XY, Yoshi's Island, Prof Layton, Sonic LW, etc)
The PR revamps the way the DSP interface works by adding a nice interface allowing for easily swappable DSP cores. Currently 2 cores are provided: A "null" core (which is the same as current upstream, fast but no audio) and an LLE core using Teakra. HLE DSP core is going to come at a later date (and potentially more DSP cores for trying out different emulation methods).
Credits go to @PSI-Rockin for making the initial version of this DSP interface and starting Teakra integration, and Citra since its Teakra integration code helped a lot
The LLE core is already booting games, but I'll merge the PR after I …
=> WIP: DSP support

src/core/kernel/resource_limits.cpp
Fixes Langrisser Re:Incarnation and probably some more stuff. Need to wait for #430 to be handled before merging this though
=> Implement GetResourceLimitValue for thread count

include/services/gsp_gpu.hpp, src/core/services/gsp_gpu.cpp
Gets Driver Regenade going further, now hangs later, seemingly wanting some camera stuff. Likely also required for other games.
=> GSP_GPU: Implement ReadHwRegs

.gitignore, CMakeLists.txt, third_party/duckstation/window_info.cpp
This is a modularization of our build targets to allow an `AlberCore` build-target.
This allows for the emulator-core to be a "headless" implementation that can be plugged into either a frontend(QT/SDL/retroarch/etc) or a unit-testing framework to test specific components of the emulator in isolation such as the DSP or shader-core and such without needing a GUI context.
=> Refactor build targets into `AlberCore`

.gitmodules, CMakeLists.txt, tests/dynapica.cpp
Implements unit-testing using Catch2. The first client of this feature is a set of unit-tests for vertex shaders. Enabled with the `ENABLE_TESTS` cmake flag, disabled by default.
This is intended for regression-testing for developers at the moment and should not block any of the current GitHub workflows. A lot of the shader-unit tests actually fail at the moment and should be addressed outside of this PR.
=> Add shader unit-testing

src/core/PICA/shader_interpreter.cpp, tests/shader.cpp
Fixes the shader-interpreter to match all of its output with the PICA200's non-IEEE conformant behavior.
The shader-interpreter now passes all unit-tests.
=> Fix shader-interpreter non-IEEE outputs

CMakeLists.txt
Because we do add_library near the end, there's a lot of duplicate checks that go like this
```
if (X)
** do find_package and stuff like that**
endif()
add_library()
if (X)
** link, compile definitions, other stuff **
endif()
```
By moving add_library at the top a lot of these can be merged into one.
Also made it so we don't compile SDL2 on Android when we don't use it there
=> Remove duplicate checks in CMakeLists

include/PICA/dynapica/shader_rec_emitter_arm64.hpp, src/core/PICA/dynapica/shader_rec_emitter_arm64.cpp
Adds `emitSafeMUL` to implement a PICA200 compliant multiplication that handles the special `0 * inf = 0` case.
Passes unit tests
=> arm64 shader JIT: Implement PICA200 compliant `MUL`

src/panda_sdl/frontend_sdl.cpp
> The scancode field is hardware specific and should be ignored unless you know what your doing. The sym field is the SDLKey value of the key being pressed or released.
=> panda_sdl: Use sym instead of scancode

.gitignore, src/core/services/ldr_ro.cpp
The old code based the data pointer used for data relocations off the buffer passed by the application. This is incorrect - the old data segment offset needs to be based upon the start of the CRO file. As a result, data relocations were written to the wrong addresses, potentially causing a crash.
Fixes the NULL pointer crash in ORAS. It likely fixes other crashes in games that use CROs, but this PR needs more testing.
=> [CRO] Fix faulty data relocations

.gitmodules, CMakeLists.txt, include/capstone.hpp, src/lua.cpp
Adds a class for disassembling code of any supported architecture with Capstone and hooks it to the scripting API for debugging uses.
Same class can later be used for implementing a proper disassembler widget in the UI, viewing recompiler output in real time, etc
=> Integrate Capstone disassembler

src/core/services/cam.cpp
The port may have a value of 3 in this function, which will cause a panic when using getSingleIndex(). getPortIndices() handles this case for us already, so the iterator value is safe to use.
Fixes a crash in The Denpa Men: They Came By Wave (USA).
=> Index with iterator value rather than getSingleIndex() in CAMService::startCapture

include/kernel/kernel.hpp, include/scheduler.hpp, include/services/service_manager.hpp, include/services/y2r.hpp, src/core/kernel/kernel.cpp, src/core/services/y2r.cpp, src/emulator.cpp
Fixes a race condition in FIFA15 that would make the game hang in the title screen. The delay needed to get FIFA not to race seems a bit high, but reasonable, and several other FMV-using games were tested without any apparent breakage. Might need more testing and tweaking though.
=> Delay Y2R completion events

src/core/fs/archive_sdmc.cpp
Needed for Miitopia's screenshot feature
=> Add SDMC::DeleteFile

CMakeLists.txt, docs/libretro/panda3ds_libretro.info, include/emulator.hpp, src/emulator.cpp, src/libretro_core.cpp, third_party/libretro/include/libretro.h
This adds support for libretro core. Audio has not been implemented yet and it might need changes in `Emulator` to allow initialization with a custom `audioDevice`. Feel free to make or request any changes.
=> Libretro core support

include/loader/ncch.hpp, src/core/loader/ncch.cpp
Fixes several encrypted dumps for later games not working, tested with Glory of Generals and Ninja Usagimaru.
Likely fixes other games reported to be broken with encrypted dumps, such as Luigi's Mansion (cc @Adamillo If you could test it pretty please)
=> Fix AES-CTR decryption for non-NCCHKey0 games

CMakeLists.txt, include/panda_qt/main_window.hpp, include/panda_qt/shader_editor.hpp, include/renderer.hpp, include/renderer_gl/renderer_gl.hpp, src/core/renderer_gl/renderer_gl.cpp, src/host_shaders/opengl_fragment_shader.frag, src/panda_qt/main_window.cpp, src/panda_qt/shader_editor.cpp
This PR adds the ability to edit the fragment shader used for the ubershader in real time, in order to be able to easily and efficiently debug it, edit it and/or profile it. Any syntax errors are written to the console and the editor is designed to be backend-agnostic, though only the OpenGL renderer has had the relevant glue code written for it atm. 
Example of live editing the ubershader to make the red component stronger:
=> Qt: Add live ubershader editor

src/core/kernel/file_operations.cpp
Fixes Luigi's Mansion on Linux which tries to change the size of a file which doesn't have write permissions...
=> Downgrade SetFileSize failure to warning

include/PICA/dynapica/shader_rec_emitter_x64.hpp, src/core/PICA/dynapica/shader_rec_emitter_x64.cpp
Adds optional support for safe mul in the x64 shader recompiler for dp3/dp4/dph/mul/mad, passes Wunk's mul testing.
=> x64 shader rec: Add support for PICA non-IEEE multiplication

include/PICA/dynapica/shader_rec.hpp, include/PICA/dynapica/shader_rec_emitter_arm64.hpp, include/PICA/dynapica/shader_rec_emitter_x64.hpp, include/config.hpp, src/config.cpp, src/core/PICA/dynapica/shader_rec.cpp, src/core/PICA/dynapica/shader_rec_emitter_arm64.cpp, src/core/PICA/dynapica/shader_rec_emitter_x64.cpp, src/core/PICA/gpu.cpp, src/libretro_core.cpp
Exposes accurate shader multiplication as an optional setting (off by default) that users can toggle & is applied when the emulator is reset. Useful for specific games like Ocarina of Time 3D which might require the shader units' weird non-IEEE multiplication being emulated properly to render correctly.
Supported in all frontends including Libretro.
=> Add accurate shader multiplication option

.github/gles.patch, include/renderer_gl/renderer_gl.hpp, src/core/renderer_gl/renderer_gl.cpp, src/host_shaders/opengl_fragment_shader.frag, src/host_shaders/opengl_vertex_shader.vert
- Made lightingLUT's type GL_TEXTURE_2D and u_tex_lighting_lut to sampler2D
- Made lightingLUT's internalFormat GL_R32F, and converting the LUT data to floats before uploading.
Internal format and format types need to match according to the spec:
My guess is the conversion to float was happening implicitly in desktop GL at some point, because `lutLookup` returns a float. The type `GL_R16` was probably interpreted as `GL_R16F` ?
The alternative to this could be using GL_R16UI, but then we'd need to convert to float on the GPU 
- Switched to using `texelFetch` instead of `texture` in the shader, since this texture is really treated as an array and we don't need filtering or interpolation
- Updated the gles.patch
- Fix light_vector not being properly updated for positional lighting
- …
=> Improve lighting

include/PICA/pica_frag_config.hpp, include/PICA/regs.hpp, include/PICA/shader_gen.hpp, src/core/PICA/shader_gen_glsl.cpp, src/core/renderer_gl/renderer_gl.cpp
Should be helpful with needing less copies for when we move to hybrid shaders
=> Remove dependency of PICA regs in fragment config

src/host_shaders/opengl_fragment_shader.frag
This PR removes Luigi's Latex suit in Luigi's Mansion
Before:
After:
=> Fix shadowed variable in ubershader

CMakeLists.txt, include/PICA/shader_gen.hpp, include/PICA/shader_gen_types.hpp
Need these enum definitions to be easily accessible from the vertex shader decompiler and any other potential GPU recompilation
=> Separate graphics API/Language types from the fragment recompiler

include/PICA/pica_frag_config.hpp, src/core/PICA/shader_gen_glsl.cpp
Saves 28 bytes from the total size of FragmentConfig
=> Use bits for scale instead of float in FragmentConfig

.github/gles.patch, docs/3ds/lighting.md, include/PICA/gpu.hpp, include/PICA/pica_frag_config.hpp, include/PICA/regs.hpp, include/PICA/shader_gen.hpp, include/renderer_gl/renderer_gl.hpp, src/core/PICA/gpu.cpp, src/core/PICA/regs.cpp, src/core/PICA/shader_gen_glsl.cpp, src/core/renderer_gl/renderer_gl.cpp, src/host_shaders/opengl_fragment_shader.frag
- Made lighting LUT texture into an RG32F lut (Light is going to need a second channel too anyway, it stores there the difference between the next value in the LUT for linear interpolation)
- Former lighting LUT texture is now the texture for all LUTs (both light and fog) and has an extra row for fog data
- Implemented fog in ubershader and specialized shaders
Before:
After:
Citra:
=> Implement fog

include/PICA/gpu.hpp, src/core/renderer_gl/renderer_gl.cpp
As the best-behaving Pokemon game, PSMD loves using 0-width texture copies and accessing textures from OoB VRAM, proving that the best anti-emulator protection is Gamefreak writing your code.
Anyways this fixes PSMD though still needs LLE DSP to get past some hangs, HLE seems to be missing something.
=> Renderer GL: Add UB checks

include/PICA/shader.hpp, include/PICA/shader_decompiler.hpp, src/core/PICA/shader_decompiler.cpp
Can now somewhat correctly decompile a basic vertex shader
```
; Example PICA200 vertex shader
; Uniforms
.fvec projection[4]
; Constants
.constf myconst(0.0, 1.0, -1.0, 0.1)
.constf myconst2(0.3, 0.0, 0.0, 0.0)
.alias  zeros myconst.xxxx ; Vector full of zeros
.alias  ones  myconst.yyyy ; Vector full of ones
; Outputs
.out outpos position
.out outclr color
; Inputs (defined as aliases for convenience)
.alias inpos v0
.alias inclr v1
.proc main
; Force the w component of inpos to be 1.0
mov r0.xyz, inpos
mov r0.w,   ones
; outpos = projectionMatrix * inpos
dp4 outpos.x, projection[0], r0
dp4 outpos.y, projection[1], r0
dp4 outpos.z, projection[2], r0
dp4 outpos.w, projection[3], r0
; outclr = inclr
mov outclr, inclr
; We're finished
end
.end
```
Becomes
```glsl
#version 410 core …
```
=> More shader->GLSL recompiler work

include/panda_qt/main_window.hpp, src/panda_qt/main_window.cpp
This moves emuThread stopping to main window closeEvent. Without this the app keeps running even if the window is closed. Also added `SDL_Quit`, but I'm not sure if it is necessary.
=> Qt: Stop emuThread on closeEvent

src/core/audio/hle_core.cpp
Fixes multiple games with HLE DSP, including Star Fox 3D and anything using the Unity engine
=> Fix HLE__DSP::RecvData

CMakeLists.txt, include/panda_qt/main_window.hpp, include/panda_sdl/frontend_sdl.hpp, include/sdl_gyro.hpp, include/services/hid.hpp, src/core/services/hid.cpp, src/panda_qt/main_window.cpp, src/panda_sdl/frontend_sdl.cpp
Allows players to control the 3DS gyroscope by moving around their controller, provided their controller has a gyroscope sensor. Makes games like Kirby's Triple Deluxe, Yoshi's New Island and Pokemon X, all of which require gyroscope to some degree, a lot more playable.
Tested with my Sony DualShock 4 on Windows.
=> Implement controller-based gyroscope on both Qt and SDL

include/sdl_gyro.hpp
Avoids copies and multiplications which MSVC was failing to optimize
=> Optimize gyro calculation

CMakeLists.txt, cmake/FindRenderDoc.cmake, include/config.hpp, include/emulator.hpp, include/renderdoc.hpp, src/config.cpp, src/emulator.cpp, src/panda_sdl/frontend_sdl.cpp, src/renderdoc.cpp, third_party/renderdoc/renderdoc_app.h
Adds support for the Renderdoc capture API for debugging hw renderers. This makes it possible to trigger captures manually from within the emulator (By pressing F11 on SDL frontend) while specifying what set of graphics API calls to include in the captures within the source code, instead of including an entire frame with thousands of calls like when using the Renderdoc UI. Additionally, programatically performing captures has other benefits such as being to capture+save the capture while Renderdoc is not running, not having to time captures when debugging < 60 fps games, not having to wade through thousands of API calls to find the sequence of calls you want to debug, and so on.
Supports all APIs that renderdoc supports out of the box (GL/GLES/DX11/DX12/Vk/etc)
=> Add renderdoc API support

.github/workflows/MacOS_Build.yml, .github/workflows/Qt_Build.yml
This PR updates the macOS build yaml with the following changes:
- Update `checkout` from v2 to v4
- Update `upload-artifact` from v2 to v4
- Removes install step for Python 3.12
Reason for changes: Resolving deprecation warnings
- v2 of `checkout` and `upload-artifact` are deprecated. 
- Python 3.12 is already installed and up to date
Testing: 
- Ensure CI still builds
=> macOS CI fixes

CMakeLists.txt, src/core/renderer_gl/renderer_gl.cpp, src/hydra_core.cpp
This adds `OPENGL_PROFILE` option to allow building for OpenGLES devices such as RPi.
=> Add build option for opengl profile

src/core/audio/miniaudio_device.cpp
On linux and macos the app crashes when enabling audio due to `frameCount * channelCount` being bigger than samples capacity. This prevents the crash, but audio still not working (only noises).
=> Prevent app crash when miniaudio samples bigger than capacity

.github/workflows/HTTP_Build.yml, .github/workflows/Hydra_Build.yml, .github/workflows/Linux_AppImage_Build.yml, .github/workflows/Linux_Build.yml, .github/workflows/Qt_Build.yml, .github/workflows/Windows_Build.yml, include/panda_qt/cheats_window.hpp, include/panda_qt/main_window.hpp, src/panda_qt/about_window.cpp, src/panda_qt/cheats_window.cpp, src/panda_qt/mappings.cpp, src/panda_qt/shader_editor.cpp
Fixes some unconventional code that would crash Qt Linguist due to declaring Q_OBJECT classes in .cpp files, necessary for doing translations (Partially supersedes #421)
=> Qt: Fix Linguist issues and format files

CMakeLists.txt
=> Qt: Add CMake target for generating translations

src/core/PICA/shader_gen_glsl.cpp
Speeds up shader compilation semi-significantly by avoiding several unecessary allocations
=> Shadergen: Pre-allocate space for shadergen string

include/sdl_sensors.hpp, src/jni_driver.cpp, src/pandroid/app/src/main/java/com/panda3ds/pandroid/AlberDriver.java, src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/GameActivity.java, src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/provider/AppDataDocumentProvider.java, src/pandroid/app/src/main/java/com/panda3ds/pandroid/math/Quaternion.java, src/pandroid/app/src/main/java/com/panda3ds/pandroid/math/Vector3.java
Implement support to accelerometer and gyroscope in android devices
=> Implement support to sensors

include/config.hpp, src/config.cpp, src/panda_qt/main_window.cpp, src/panda_sdl/frontend_sdl.cpp
Optionally remembers window position and size between runs so people don't have to readjust it on every run.
Currently disabled by default to avoid the same funny oddities that sometimes happen with this setting in Redux, can be enabled from the config file though (Or the config UI in the near future)
=> Qt: Optionally remember window pos/size

include/audio/miniaudio_device.hpp, src/core/audio/miniaudio_device.cpp, src/emulator.cpp
Fixes audio bugs & crashes on Android in HLE-audio-enabled builds.
=> Audio: Properly close audio device on emulator destruction

include/renderer_null/renderer_null.hpp, src/panda_sdl/frontend_sdl.cpp
Meant to improve performance on the null renderer, as some people may prefer to play games with only audio (eg partially-sighted people)
=> Renderer: Improve null renderer performance

src/panda_qt/main_window.cpp
MacOS requires a 'global' menubar to be available (e.g. QtMenuBar(nullptr)).
Please test if this doesn't break anything on Windows/Linux..
=> Qt UI: fix menu bar on MacOS

include/fs/archive_base.hpp, src/core/fs/archive_card_spi.cpp, src/core/fs/archive_ext_save_data.cpp, src/core/fs/archive_ncch.cpp, src/core/fs/archive_save_data.cpp, src/core/fs/archive_sdmc.cpp, src/core/fs/archive_self_ncch.cpp, src/core/fs/archive_system_save_data.cpp, src/core/fs/archive_twl_photo.cpp, src/core/fs/archive_twl_sound.cpp, src/core/fs/archive_user_save_data.cpp, src/core/services/service_manager.cpp
Makes filesystem code human-readable, makes it easier to support both UTF16 and ASCII paths in the same archive, allows more things to boot like Anemone3DS
=> Make filesystem decent, part 1

include/panda_qt/main_window.hpp, src/panda_qt/main_window.cpp
Fixes the mouse code not handling "dragging" the mouse properly on Qt, evident in eg gpu_test.3dsx
=> Qt: Handle mouse move events properly

include/config.hpp, include/services/cfg.hpp, src/config.cpp, src/core/services/cfg.cpp, src/core/services/service_manager.cpp, src/panda_qt/config_window.cpp
Allows you to change what language games themselves use
=> Make system language configurable

src/config.cpp, src/emulator.cpp
This fixes MacOS app bundles, as the emulator cannot write the config file into the app bundle.
=> Store configuration file in AppData root if not in working directory

.github/gles.patch, CMakeLists.txt, include/emulator.hpp, include/renderer.hpp, include/renderer_gl/renderer_gl.hpp, src/core/renderer_gl/renderer_gl.cpp, src/emulator.cpp, src/host_shaders/opengl_es_display.frag, src/host_shaders/opengl_es_display.vert, src/hydra_core.cpp, src/jni_driver.cpp, src/libretro_core.cpp, src/panda_qt/main_window.cpp, src/panda_qt/screen.cpp, src/panda_sdl/frontend_sdl.cpp
This should fix GLES support on desktop platforms on both SDL and Qt.
Several devices such as the Raspberry Pi 5 and emulation handhelds (eg RK3588) don't support desktop GL. This allows users to play games on those, and also turns off ubershaders on them since none of them can actually run any well with them on.
=> Support GLES on desktop

src/panda_qt/main.cpp, src/panda_qt/main_window.cpp, src/panda_qt/screen.cpp
Qt will only create a Wayland surface when show() is called on the main window and on the ScreenWidget. Thus, call the function before creating the GL context.
Doesn't cause regressions on XWayland, untested in other platforms.
Fixes #586
=> Qt: Fix Wayland support

include/cpu_dynarmic.hpp, include/kernel/kernel.hpp, src/core/kernel/kernel.cpp, src/core/services/ldr_ro.cpp
Significantly reduces stutter in games like Pokemon X/Y and ORAS that constantly switch between CROs
=> Add Luma icache SVCs and don't flush entire code cache when loading/unloading CROs

include/kernel/kernel.hpp, include/kernel/resource_limits.hpp, include/memory.hpp, src/core/kernel/memory_management.cpp, src/core/services/apt.cpp
Should improve stability in most games that use extended memory, such as Pokemon SM/USUM, Smash Bros, Mario Maker, and so on
=> Temporarily give 80MB of FCRAM to all apps

CMakeLists.txt, include/audio/audio_device.hpp, include/audio/audio_device_interface.hpp, include/audio/libretro_audio_device.hpp, include/audio/miniaudio_device.hpp, include/emulator.hpp, src/core/audio/miniaudio_device.cpp, src/libretro_core.cpp
This adds support for audio to the libretro core. It is a working solution but a proper solution will require refactoring the MiniaudioDevice class to avoid code duplication. I’m open to any suggestions you may have.
=> [WIP] Libretro: Add audio support

src/core/PICA/regs.cpp
Fixes graphics in some games exploding due to wrong uniform values
=> GPU registers: Fix writes to some registers ignoring the mask

CMakeLists.txt, src/miniaudio/miniaudio.cpp, src/miniaudio/miniaudio.m, third_party/ios_toolchain/ios.toolchain.cmake
Allows building the core for iOS with a small patch to SDL, via `cmake -B build -DENABLE_VULKAN=OFF -DBUILD_HYDRA_CORE=ON -DCMAKE_TOOLCHAIN_FILE=third_party/ios_toolchain/ios.toolchain.cmake -DPLATFORM=SIMULATORARM64 -DDEPLOYMENT_TARGET="13.0"`
=> [Core] Improve iOS compilation workflow

include/config.hpp, include/renderer.hpp, include/renderer_gl/textures.hpp, include/renderer_mtl/mtl_texture.hpp, src/config.cpp, src/core/renderer_gl/renderer_gl.cpp, src/core/renderer_mtl/renderer_mtl.cpp, src/emulator.cpp, src/libretro_core.cpp, src/panda_qt/config_window.cpp
Fixes graphics in games that reuse VRAM for textures, eg PSMD/NSMB2/OoT/Yokai Watch. Can be turned off in case of perf concerns
=> Add optional texture hashing

CMakeLists.txt, include/emulator.hpp, include/kernel/kernel.hpp, include/lua_manager.hpp, include/panda_qt/main_window.hpp, include/panda_qt/thread_debugger.hpp, include/services/service_intercept.hpp, include/services/service_manager.hpp, src/core/kernel/idle_thread.cpp, src/core/kernel/kernel.cpp, src/core/kernel/threads.cpp, src/core/services/service_manager.cpp, src/emulator.cpp, src/lua.cpp, src/panda_qt/main_window.cpp, src/panda_qt/thread_debugger.cpp
Service call intercepts (Allows you to inject Lua code when sysmodule functions are called, or handle the sysmodule entirely from Lua):
```lua
OpenFile = 0x080201C2
Pand.addServiceIntercept("fs:USER", OpenFile)
function interceptService(service, func, buffer)
print("Intercepted a function from the", service, "module")
if service == "fs:USER" and func == OpenFile then
print("OpenFile was called, let's nuke it")
Pand.write32(buffer + 4, -1)
-- Tell the C++ side we handled this service call ourselves and it doesn't need to do anything
return true
end
-- Let C++ handle the service call
return false
end
```
Thread debugger draft:
=> Add service call intercepts via Lua & thread debugger draft

src/core/PICA/gpu.cpp
This is a regression that seems to have been introduced when adding hw shaders. Fixes VertexShaderOutputMask emulation in the shader interpreter & CPU JIT backends.
This fixes various games that regressed when not using hw shaders, such as Pokemon Super Mystery Dungeon.
=> GPU: Fix VertexShaderOutputMask in non-accelerated draws

include/renderer_gl/renderer_gl.hpp, src/core/renderer_gl/renderer_gl.cpp
Improves performance a *lot* on devices where glBufferSubData is slow, as UBOs now use persistent-mapped storage. Tested on an M3 Mac, where games with lots of buffer upload would completely choke on uploading data to the GPU.
=> GL: Use StreamBuffer for shadergen UBOs
