wheremyfoodat/Panda3DS

- readme.md
> Add a Discord link that actually links to the discord

- include/PICA/regs.hpp
> Add TexEnv PICA register offsets

- .github/workflows/Linux_Build.yml
- .github/workflows/MacOS_Build.yml
- .github/workflows/Windows_Build.yml
- CMakeLists.txt
- include/PICA/gpu.hpp
- include/PICA/regs.hpp
- include/helpers.hpp
- include/opengl.hpp
- include/renderer_gl/renderer_gl.hpp
- include/services/hid.hpp
- src/core/PICA/gpu.cpp
- src/core/PICA/regs.cpp
- src/core/kernel/directory_operations.cpp
- src/core/kernel/idle_thread.cpp
- src/core/loader/ncch.cpp
- src/core/memory.cpp
- src/core/renderer_gl/renderer_gl.cpp
- src/core/services/apt.cpp
- src/core/services/cecd.cpp
- src/core/services/hid.cpp
Working to make our GPU more lit than it already is.
> Implement Fragment Lighting (and clipping planes)

- readme.md
This is the GPROAT (Greatest Pull Request of all time)
> Update Readme with controls

- include/renderer_gl/renderer_gl.hpp
- include/renderer_gl/surface_cache.hpp
- include/renderer_gl/surfaces.hpp
> Color and depth cache updates

- .gitmodules
- CMakeLists.txt
- include/PICA/gpu.hpp
- include/emulator.hpp
- include/httpserver.hpp
- include/renderer_gl/renderer_gl.hpp
- src/core/renderer_gl/renderer_gl.cpp
- src/emulator.cpp
- src/httpserver.cpp
PANDA? PANDA.
(repeat 31 times)
> Add initial http server stuff

- include/kernel/config_mem.hpp
- src/core/memory.cpp
Ran clang-format on affected files only.
> Stub reads for WIFI MAC address in ConfigMem

- include/action_replay.hpp
- include/cheats.hpp
- include/services/hid.hpp
- include/services/service_manager.hpp
- src/core/action_replay.cpp
- src/core/cheats.cpp
- src/emulator.cpp
Using cheats in Panda3DS reports you to the FBI. Tread carefully.
> More cheating

- .github/mac-bundle.sh
- .github/workflows/Linux_Build.yml
- .github/workflows/MacOS_Build.yml
- .github/workflows/Windows_Build.yml
- CMakeLists.txt
- include/PICA/gpu.hpp
- include/renderer.hpp
- include/renderer_gl/renderer_gl.hpp
- include/renderer_null/renderer_null.hpp
- include/renderer_sw/renderer_sw.hpp
- include/renderer_vk/renderer_vk.hpp
- include/renderer_vk/vk_debug.hpp
- include/renderer_vk/vulkan_api.hpp
- readme.md
- src/core/PICA/gpu.cpp
- src/core/renderer_gl/renderer_gl.cpp
- src/core/renderer_null/renderer_null.cpp
- src/core/renderer_sw/renderer_sw.cpp
- src/core/renderer_vk/renderer_vk.cpp
- src/core/renderer_vk/vk_debug.cpp
- src/core/renderer_vk/vulkan_api.cpp
- src/emulator.cpp
> Initialize Vulkan Context

- include/cheats.hpp
- include/emulator.hpp
- src/core/cheats.cpp
- src/emulator.cpp
> Better cheat interface

- include/emulator.hpp
- include/httpserver.hpp
- src/emulator.cpp
- src/httpserver.cpp
> Add resume/pause button, some hotkeys, more HTTPanda commands

- include/emulator.hpp
- include/httpserver.hpp
- src/core/loader/ncch.cpp
- src/emulator.cpp
- src/httpserver.cpp
> Add load_rom http server command

- include/PICA/regs.hpp
- include/renderer_gl/gl_state.hpp
- include/renderer_gl/opengl.hpp
- include/renderer_gl/renderer_gl.hpp
- include/renderer_gl/surfaces.hpp
- src/core/renderer_gl/gl_state.cpp
- src/core/renderer_gl/renderer_gl.cpp
- src/core/services/gsp_gpu.cpp
* Implements stencil testing and logic op
* Respects the depth write register
* Initial implementation of buffer clears
Improves 3D Land rendering
> Depth buffer fixes

- include/io_file.hpp
- src/core/fs/archive_save_data.cpp
- src/io_file.cpp
Fixes a small memory leak and some filesystem bugs
Gets Captain Toad working in my threading branch
> [FS] Better file flushing

- include/helpers.hpp
> Fix helpers.hpp on Android

- include/kernel/config_mem.hpp
- src/core/memory.cpp
Required by toon shading devkitpro demo
> [Memory] Add 3D Slider shared page value

- include/services/boss.hpp
- src/core/services/boss.cpp
Get's Yoshi's New Island working (Original PR was #162 but I botched it)
> Stub BOSS::CancelTask

- CMakeLists.txt
- include/kernel/handles.hpp
- include/logger.hpp
- include/result/result.hpp
- include/result/result_cfg.hpp
- include/services/act.hpp
- include/services/cfg.hpp
- include/services/http.hpp
- include/services/service_manager.hpp
- src/core/services/act.cpp
- src/core/services/cfg.cpp
- src/core/services/http.cpp
- src/core/services/service_manager.cpp
Currently Chibi-Robo crashes on a null access so need more work before merging, might be a thread issue >_<
> HLE improvements for Chibi-Robo et al

- CMakeLists.txt
- include/kernel/handles.hpp
- include/logger.hpp
- include/services/service_manager.hpp
- include/services/ssl.hpp
- src/core/services/service_manager.cpp
- src/core/services/ssl.cpp
Gets Ultimate NES booting. Does not handle multiple sessions correctly yet, but there's a warning for that
> Initial implementation of SSL service

- include/PICA/shader.hpp
- src/core/PICA/dynapica/shader_rec_emitter_x64.cpp
- src/core/PICA/shader_interpreter.cpp
Makes Luigi's Moon: Dark Mansion go in-game, still missing in interpreter
> [Shader JIT] Add DPHI

- src/core/services/cfg.cpp
> *Actually* make 3DS report the auto-detected region

- src/core/fs/archive_ext_save_data.cpp
- src/core/fs/archive_save_data.cpp
Fixes Bravely Default, probably others
> Add forgotten fclose calls

- include/services/frd.hpp
- src/core/services/frd.cpp
Makes Kid Icarus Uprising do stuff
> Add FRD::UpdateGameModeDescription

- include/services/nfc.hpp
- src/core/memory.cpp
- src/core/services/nfc.cpp
Implement some NFC things that will be needed for implementing Amiibos fully. Also fixes some games like Captain Toad
> Amiibo stuffs

- include/services/boss.hpp
- src/core/services/boss.cpp
This makes Jump Trials Supreme go in-game, and most likely various other titles that complained about the BOSS service
> Stub more BOSS functions

- include/services/ac.hpp
- src/core/services/ac.cpp
Required for Rollercoaster Tycoon, Ultimate NES remix, probably more
> AC stubs (CancelConnectAsync, CreateDefaultConfig)

- include/services/ac.hpp
- include/services/frd.hpp
- src/core/services/ac.cpp
- src/core/services/frd.cpp
Used by Skylanders Racing et al
> FRD and AC stuff

- include/config.hpp
- src/config.cpp
SD cards are not yet implemented but I'd rather do it now than later
> Add SD card configs

- .gitmodules
- CMakeLists.txt
> Set MacOS deployment target

- src/core/fs/archive_self_ncch.cpp
Since we currently don't support loading game updates or DLC, reading the update RomFS just reads the cartridge RomFS.
When we do decide to support updates/DLC, we will have to implement overlaying the update filesystems with the ROM filesystems (RomFS/ExeFS) if an update/DLC is loaded
> Stub update RomFS

- include/fs/archive_base.hpp
- include/services/fs.hpp
- src/core/services/fs.cpp
Needed for escapeVektor, Cursed Castilla and more
> [FS] AbnegateAccessRight, SetArchivePriority, GetArchiveResource

- CMakeLists.txt
Utilize the `GPU_DEBUG_INFO` flag to conditionally compile spirv files
with debugging information.
---
Without `GPU_DEBUG_INFO`:
With `GPU_DEBUG_INFO`:
> vulkan: Add shader debugging information

- include/services/y2r.hpp
- src/core/services/y2r.cpp
ευγενικά ειναι το πρωτο μου pull request :D
> added some y2r service calls

- src/core/services/nfc.cpp
Gets Captain Toad nice and ready for some amiibo impl testing
> Add NFC::CommunicationGetResult

- readme.md
> Add ctru-rs to readme

- include/kernel/config_mem.hpp
- include/kernel/handles.hpp
- src/core/memory.cpp
- src/core/services/service_manager.cpp
> Don't die on ns:s, add wifi level config mem address

- .gitmodules
- CMakeLists.txt
- include/emulator.hpp
- include/lua.hpp
- src/emulator.cpp
- src/lua.cpp
> Embed LuaJIT part 1

- include/services/ac.hpp
- include/services/cfg.hpp
- include/services/frd.hpp
- include/services/ndm.hpp
- src/core/services/ac.cpp
- src/core/services/cfg.cpp
- src/core/services/frd.cpp
- src/core/services/ndm.cpp
Mainly focuses on CFG/AC/FRD, lets me get friend list and some more apps booting on my local (NOT on this upstream)
> Add HLE stuff to boot more OS apps

- include/fs/archive_base.hpp
- include/services/cfg.hpp
- include/services/fs.hpp
- src/core/fs/archive_ncch.cpp
- src/core/services/cfg.cpp
- src/core/services/fs.cpp
Add FS::RenameFile (Still crashes due to archives not implementing it, but the service itself is there), add CFG::TranslateCountryInfo and stub shared data archive 00010602 ("Non-Nintendo TLS Root-CA Certificates" according to 3DBrew)
> HLE stuffs

- .github/linux-appimage-qt.sh
- .github/workflows/Qt_Build.yml
* Change to different Qt6 PPA
* Specify Qmake6
> Add Qt AppImage

- include/PICA/gpu.hpp
- include/emulator.hpp
- include/panda_qt/main_window.hpp
- include/panda_qt/screen.hpp
- include/renderer.hpp
- src/core/renderer_gl/renderer_gl.cpp
- src/emulator.cpp
- src/panda_qt/main_window.cpp
- src/panda_qt/screen.cpp
Does most of the work for #190, so I'll be closing that and resizing should be implemented relatively soon in panda-qt.
panda-sdl will get resizing sometime in the future instead.
> Make emulator output size properly configurable

- include/memory.hpp
- include/panda_qt/main_window.hpp
- src/core/memory.cpp
Will check if it fixes inazuma eleven later
> Better MAC address handling

- CMakeLists.txt
Most use of this seems to be accidental soooo
> Disable dev panics by default

- .github/workflows/HTTP_Build.yml
- .github/workflows/Hydra_Build.yml
- .github/workflows/Linux_AppImage_Build.yml
- .github/workflows/Linux_Build.yml
- .github/workflows/Qt_Build.yml
Because newer libstdc++ is hopelessly broken otherwise
> Update to Clang 17 on CI

- src/core/services/apt.cpp
Fixes Monster Strike (Japan) and probably some others
> [APT] Gracefully handle SetApplicationCpuTimeLimit with invalid inputs

- src/core/kernel/file_operations.cpp
- src/core/kernel/kernel.cpp
> Filesystem fixes

- src/jni_driver.cpp
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/AlberDriver.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/GameActivity.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/game/AlberInputListener.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/game/DrawerFragment.java
- src/pandroid/app/src/main/res/drawable/ic_exit.xml
- src/pandroid/app/src/main/res/drawable/ic_shortcut.xml
- src/pandroid/app/src/main/res/layout/drawer_game_container.xml
- src/pandroid/app/src/main/res/layout/fragment_game_drawer.xml
- src/pandroid/app/src/main/res/layout/game_activity.xml
- src/pandroid/app/src/main/res/menu/game_drawer_actions.xml
- src/pandroid/app/src/main/res/values-pt-rBR/strings.xml
- src/pandroid/app/src/main/res/values/strings.xml
- src/pandroid/app/src/main/res/values/styleable.xml
Add a drawer when click the back button on emulation.
> Pandroid: Drawer

- src/core/PICA/dynapica/shader_rec_emitter_x64.cpp
Should fix graphics in a bunch of games
> Fix cmp in x64 shader JIT

- include/emulator.hpp
- src/emulator.cpp
- src/panda_qt/main_window.cpp
@OFFTKP What if you tested on Linux 😳
> More app folder utilities & "Open Panda3DS folder" button

- src/core/services/cam.cpp
> clang-format and IWYU fixes

- include/fs/archive_sdmc.hpp
- include/services/fs.hpp
- src/core/fs/archive_sdmc.cpp
- src/core/services/fs.cpp
> Implement SDMC Write-Only archive

- include/android_utils.hpp
- src/io_file.cpp
- src/jni_driver.cpp
- src/pandroid/app/src/main/AndroidManifest.xml
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/AlberDriver.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/MainActivity.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/base/LoadingAlertDialog.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/game/DrawerFragment.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/game/LuaDialogFragment.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/main/GamesFragment.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/data/game/GameMetadata.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/utils/Constants.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/utils/FileUtils.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/utils/GameUtils.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/view/code/BasicTextEditor.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/view/code/syntax/PatternUtils.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/view/utils/PerformanceView.java
- src/pandroid/app/src/main/res/layout/dialog_loading.xml
- src/pandroid/app/src/main/res/values-pt-rBR/strings.xml
- src/pandroid/app/src/main/res/values/strings.xml
In more recents android version, android dont like fs/io operations for user storage, Google recomends use [SAF](https://developer.android.com/guide/topics/providers/document-provider) for manage all files, in moment SAF is many used in java code of this project, but not for load rom files, this pr migrate rom load to SAF implementation.
(thanks for yuzu developers!!)
> Pandroid: Storage Access Framework (SAF)

- .gitmodules
- CMakeLists.txt
- include/audio/dsp_core.hpp
- include/audio/miniaudio_device.hpp
- include/audio/teakra_core.hpp
- include/config.hpp
- include/emulator.hpp
- include/ring_buffer.hpp
- src/config.cpp
- src/core/audio/miniaudio_device.cpp
- src/core/audio/teakra_core.cpp
- src/emulator.cpp
- src/miniaudio.cpp
- src/panda_qt/main_window.cpp
- src/panda_sdl/frontend_sdl.cpp
Adds audio output and some settings to control vsync and whether audio output is enabled
Note: This was tested with the WIP DSP JIT, audio will be too slow with Teakra interpreter which is part of why this is all off by default. To make audio acutally bearable, either the DSP JIT or HLE audio need to be done.
> Get audio output working with LLE DSP

- .gitmodules
This should hopefully fix the build since Citra's boost fork is down now
> Fix boost submodule

- readme.md
I updated the readme to include the controls for the dpad as well as clarify that wasd is for the analog stick.
> Add dpad controls to readme.

- include/services/y2r.hpp
- src/core/services/y2r.cpp
Fixes TMNT and possibly others. Also waiting on #430 to be settled in order to merge
> Y2R: Stub IsFinishedSending/Receiving functions

- src/core/PICA/dynapica/shader_rec_emitter_arm64.cpp
- tests/shader.cpp
Implements log2 and exp2 for the arm64 shader-jit.
Includes some maintenance adjustments for the shader JIT unit tests as well to avoid code duplication.
> Implement arm64 `LG2`/`EX2`

- src/core/PICA/shader_interpreter.cpp
- tests/shader.cpp
> Implement shader-interpreter relative `MOVA` addressing

- include/panda_qt/main_window.hpp
- src/panda_qt/main_window.cpp
Tested on Windows with a DS4, would be nice if someone could test on Mac/Linux
> Add controller support to Qt

- include/PICA/gpu.hpp
- include/PICA/regs.hpp
- src/core/PICA/gpu.cpp
Fixes broken graphics in Pokemon Mystery Dungeon: Gates To Infinity, Super Pokemon Mystery Dungeon, Pokedex 3D and more
> Implement GPUREG_VSH_OUTMAP_MASK

- include/PICA/shader.hpp
Needed for PSMD & probably others
> GPU: Handle invalid floating point uniform writes

- third_party/opengl/opengl.hpp
> Add UBO support to opengl.hpp

- src/libretro_core.cpp
This add support for touchscreen input. Do you think that they should be toggle-able with settings like in the citra core?
```cpp
{"panda3ds_mouse_touchscreen", "Simulate touchscreen with mouse; enabled|disabled"},
{"panda3ds_touch_touchscreen", "Simulate touchscreen with touch; enabled|disabled"},
```
I can also add support for joystick emulation but that needs to render a pointer and I wasn't able to do it by following an implementation like that in citra core [here](https://github.com/libretro/citra/blob/2d67658e85de4767c0eefeb2829d710401c5c802/src/citra_libretro/input/mouse_tracker.cpp#L184).
> Libretro: Add support for touch input

- src/miniaudio.cpp
> Add period at the end of a sentence

- include/crypto/aes_engine.hpp
- src/core/crypto/aes_engine.cpp
- src/core/loader/ncch.cpp
- src/emulator.cpp
Needed for decrypting some titles, mostly e-shop ones.
> Implement seed crypto

- include/PICA/shader.hpp
- src/core/PICA/shader_interpreter.cpp
- tests/PICA_LITP/Makefile
- tests/PICA_LITP/source/main.c
- tests/PICA_LITP/source/vshader.v.pica
This will probably need a lot of fuzzing to figure out the proper result for NaNs/infinities but that's a task for another day. Pictures of the test from the emulator and @profi200 's 3DS
> PICA: Add LITP test + interpreter implementation

- include/audio/dsp_core.hpp
- include/audio/hle_core.hpp
- include/audio/null_core.hpp
- include/audio/teakra_core.hpp
- src/core/audio/hle_core.cpp
- src/core/audio/null_core.cpp
- src/emulator.cpp
Still WIP, as I need to look into some hangs in Yoshi's Island/PSMD.
Fixes various hangs in several games, including Pokemon XY/ORAS, Yoshi's Island, Sonic Lost World, Pokemon GTI/SMD and more
> Fixing remaining HLE DSP hangs

- .github/workflows/MacOS_Build.yml
- .github/workflows/Qt_Build.yml
- src/core/audio/hle_core.cpp
Tested to fix PSMD and Yoshi's Island on HLE DSP, should also fix Pokemon XY/ORAS/GTI, Dr. Mario, Star Fox 64, and hopefully a lot more.
I aged like 30 years debugging this please over the course of 2 weeks, I will now be going into hibernation.
> HLE DSP: Fix source resetting

- src/host_shaders/opengl_fragment_shader.frag
> OpenGL: Fix fragment shader compilation error

- .gitmodules
- CMakeLists.txt
- include/audio/aac.hpp
- include/audio/aac_decoder.hpp
- include/audio/hle_core.hpp
- src/core/audio/aac_decoder.cpp
- src/core/audio/hle_core.cpp
Tested and verified to work fine with Pokemon X/Y, though currently disabled until HLE DSP mixing/output is properly implemented. Uploaded a small AAC audio dump from the decoder on the discord server
> HLE DSP: Implement AAC audio decoding

- src/libretro_core.cpp
This does not fix or add anything. It completes the code formatting and optimizes default values in some settings.
> Libretro: Complete code formatting

- .github/workflows/Hydra_Build.yml
- .github/workflows/Linux_AppImage_Build.yml
- .github/workflows/Linux_Build.yml
- .github/workflows/Qt_Build.yml
- CMakeLists.txt
- include/PICA/pica_frag_config.hpp
- include/PICA/regs.hpp
- include/PICA/shader_gen.hpp
- include/renderer_gl/gl_driver.hpp
- include/renderer_gl/renderer_gl.hpp
- src/core/PICA/shader_gen_glsl.cpp
- src/core/renderer_gl/renderer_gl.cpp
This should fix games that require logic ops like Super Mario 3D Land on GLES devices (mostly mobile)
> GLES: Implement logic ops via fb fetch

- src/jni_driver.cpp
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/AlberDriver.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/GameActivity.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/preferences/AdvancedPreferences.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/preferences/screen_editor/ScreenEditorPreference.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/data/config/GlobalConfig.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/view/PandaGlRenderer.java
- src/pandroid/app/src/main/res/values-pt-rBR/strings.xml
- src/pandroid/app/src/main/res/values/strings.xml
- src/pandroid/app/src/main/res/xml/advanced_preferences.xml
- Implement option to enable accurate shader multiplication
- Fix Screen layout editor
> Implement accurate shader multiplication option

- src/jni_driver.cpp
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/GameActivity.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/base/BasePreferenceFragment.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/app/preferences/GeneralPreferences.java
- src/pandroid/app/src/main/java/com/panda3ds/pandroid/utils/FileUtils.java
- src/pandroid/app/src/main/res/values-pt-rBR/strings.xml
- src/pandroid/app/src/main/res/values/strings.xml
- src/pandroid/app/src/main/res/xml/general_preference.xml
- Option to import keys
- Option to import seeddb.bin
- FIx some crashes
> Import key option in android

- include/align.hpp
https://git.libretro.com/libretro/Panda3DS/-/pipelines/310865
> libretro: win32 build fix

- include/emulator.hpp
- src/jni_driver.cpp
Needed for exposing the "enable audio" setting on Android
> JNI driver: Add setAudioEnabled hook

- CMakeLists.txt
- docs/translations/es.ts
- src/panda_qt/translations.cpp
Every string is translated except for two of the color themes `Cream` and `Greetings Cat` as I'm unsure where to literally translate it or keep the original name.
> Qt: Add Spanish translation

- .github/workflows/MacOS_Build.yml
- .github/workflows/Qt_Build.yml
- CMakeLists.txt
Please hold on merging until I test the artifacts one last time..
> Add MacOS ARM64 and Universal builds to GitHub Actions

- CMakeLists.txt
- include/fs/archive_base.hpp
- include/fs/archive_twl_photo.hpp
- include/fs/archive_twl_sound.hpp
- include/services/fs.hpp
- src/core/fs/archive_system_save_data.cpp
- src/core/fs/archive_twl_photo.cpp
- src/core/fs/archive_twl_sound.cpp
- src/core/services/fs.cpp
> FS: Add the Twilight Zone

- src/panda_qt/config_window.cpp
> Prevent selecting Vulkan renderer in Qt frontend and present a message

- CMakeLists.txt
Fixes versioning from git when git tags are missing (eg. CI)
> Fix git versioning

- include/renderer.hpp
- src/core/renderer_gl/renderer_gl.cpp
- src/core/renderer_mtl/renderer_mtl.cpp
- src/renderer.cpp
Fixes graphics in NSMB2 and probably other games
> GPU: Add sw texture copies

- src/core/kernel/file_operations.cpp
Fixes not being able to import save files in Pokemon XY from Citra/hw
> FS: Add missing file seeks

- include/renderer.hpp
- include/renderer_gl/renderer_gl.hpp
- include/renderer_mtl/renderer_mtl.hpp
- src/core/renderer_gl/renderer_gl.cpp
- src/core/renderer_mtl/renderer_mtl.cpp
- src/panda_qt/main_window.cpp
TODO:
- ~~Clear the window before drawing the output since we're not doing a fullscreen draw anymore~~
- Make sure there's no multithreading race conditions in the Qt frontend
> SDL/Qt: Better resizing & fullscreen support

- CMakeLists.txt
- include/capstone.hpp
- include/emulator.hpp
- include/panda_qt/cpu_debugger.hpp
- include/panda_qt/disabled_widget_overlay.hpp
- include/panda_qt/main_window.hpp
- src/panda_qt/cpu_debugger.cpp
- src/panda_qt/main_window.cpp
Not quite thread-safe and should generally not be used while the emulator is running, but good enough for now
> Qt: Initial CPU debugger implementation

- CMakeLists.txt
- include/lua_manager.hpp
- include/services/service_manager.hpp
- include/services/service_map.hpp
- src/core/services/service_manager.cpp
- src/lua.cpp
> Upgrade Lua service intercepts pt 2

- include/services/cecd.hpp
- src/core/services/cecd.cpp
Gets Dead or Alive Dimensions ingame
> CECD: Stub GetChangeStateEventHandle

- CMakeLists.txt
- include/PICA/dynapica/shader_rec_emitter_x64.hpp
- include/PICA/dynapica/x64_regs.hpp
- include/audio/dsp_binary.hpp
- include/audio/dsp_core.hpp
- include/audio/hle_core.hpp
- include/audio/null_core.hpp
- include/audio/teakra_core.hpp
- include/emulator.hpp
- include/panda_qt/dsp_debugger.hpp
- include/panda_qt/main_window.hpp
- src/core/audio/hle_core.cpp
- src/core/audio/teakra_core.cpp
- src/panda_qt/cpu_debugger.cpp
- src/panda_qt/dsp_debugger.cpp
- src/panda_qt/main_window.cpp
> Add DSP debugger

- include/audio/hle_core.hpp
- src/core/audio/hle_core.cpp
Fixes audio in Detective Pikachu on #722
> HLE DSP: Implement partial embedded buffer updates
